import { Toaster } from '@/components/ui/sonner';
import { Undo2Icon } from 'lucide-react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <main className='h-screen flex items-center justify-center bg-muted '>
          <div className='bg-white p-8 shadow-md w-full max-w-sm h-fit grid place-items-center rounded-md relative'>
            <Link
              href={'/'}
              className='text-xs font-medium absolute flex gap-2 text-muted-foreground top-4 left-4'
            >
              <Undo2Icon className='size-4' /> Go Back
            </Link>
            {children}
            <Toaster richColors />
          </div>
        </main>
      </body>
    </html>
  );
}
