import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons:
    'https://res.cloudinary.com/dynscts1t/image/upload/v1710035278/logo-adrian_bul6an.svg',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body>
        {children}
        {/* <Toaster richColors /> */}
      </body>
    </html>
  );
}
